[package]
name = "parser-ui"
version = "0.1.0"
authors = ["Ben Ali <somcoder@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"

parser-util = { path = "../parser-util" }